import paddle
import math
from x2paddle.op_mapper.onnx2paddle import onnx_custom_layer as x2paddle_nn

class ONNXModel(paddle.nn.Layer):
    def __init__(self):
        super(ONNXModel, self).__init__()
        self.x2paddle_classifier_1_weight = self.create_parameter(shape=[4, 1280], attr='x2paddle_classifier_1_weight', dtype='float32', default_initializer=paddle.nn.initializer.Constant(value=0.0))
        self.x2paddle_classifier_1_bias = self.create_parameter(shape=[4], attr='x2paddle_classifier_1_bias', dtype='float32', default_initializer=paddle.nn.initializer.Constant(value=0.0))
        self.conv0 = paddle.nn.Conv2D(in_channels=3, out_channels=32, kernel_size=[3, 3], stride=2, padding=1)
        self.conv1 = paddle.nn.Conv2D(in_channels=32, out_channels=32, kernel_size=[3, 3], padding=1, groups=32)
        self.conv2 = paddle.nn.Conv2D(in_channels=32, out_channels=16, kernel_size=[1, 1])
        self.conv3 = paddle.nn.Conv2D(in_channels=16, out_channels=96, kernel_size=[1, 1])
        self.conv4 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[3, 3], stride=2, padding=1, groups=96)
        self.conv5 = paddle.nn.Conv2D(in_channels=96, out_channels=24, kernel_size=[1, 1])
        self.conv6 = paddle.nn.Conv2D(in_channels=24, out_channels=144, kernel_size=[1, 1])
        self.conv7 = paddle.nn.Conv2D(in_channels=144, out_channels=144, kernel_size=[3, 3], padding=1, groups=144)
        self.conv8 = paddle.nn.Conv2D(in_channels=144, out_channels=24, kernel_size=[1, 1])
        self.conv9 = paddle.nn.Conv2D(in_channels=24, out_channels=144, kernel_size=[1, 1])
        self.conv10 = paddle.nn.Conv2D(in_channels=144, out_channels=144, kernel_size=[3, 3], stride=2, padding=1, groups=144)
        self.conv11 = paddle.nn.Conv2D(in_channels=144, out_channels=32, kernel_size=[1, 1])
        self.conv12 = paddle.nn.Conv2D(in_channels=32, out_channels=192, kernel_size=[1, 1])
        self.conv13 = paddle.nn.Conv2D(in_channels=192, out_channels=192, kernel_size=[3, 3], padding=1, groups=192)
        self.conv14 = paddle.nn.Conv2D(in_channels=192, out_channels=32, kernel_size=[1, 1])
        self.conv15 = paddle.nn.Conv2D(in_channels=32, out_channels=192, kernel_size=[1, 1])
        self.conv16 = paddle.nn.Conv2D(in_channels=192, out_channels=192, kernel_size=[3, 3], padding=1, groups=192)
        self.conv17 = paddle.nn.Conv2D(in_channels=192, out_channels=32, kernel_size=[1, 1])
        self.conv18 = paddle.nn.Conv2D(in_channels=32, out_channels=192, kernel_size=[1, 1])
        self.conv19 = paddle.nn.Conv2D(in_channels=192, out_channels=192, kernel_size=[3, 3], stride=2, padding=1, groups=192)
        self.conv20 = paddle.nn.Conv2D(in_channels=192, out_channels=64, kernel_size=[1, 1])
        self.conv21 = paddle.nn.Conv2D(in_channels=64, out_channels=384, kernel_size=[1, 1])
        self.conv22 = paddle.nn.Conv2D(in_channels=384, out_channels=384, kernel_size=[3, 3], padding=1, groups=384)
        self.conv23 = paddle.nn.Conv2D(in_channels=384, out_channels=64, kernel_size=[1, 1])
        self.conv24 = paddle.nn.Conv2D(in_channels=64, out_channels=384, kernel_size=[1, 1])
        self.conv25 = paddle.nn.Conv2D(in_channels=384, out_channels=384, kernel_size=[3, 3], padding=1, groups=384)
        self.conv26 = paddle.nn.Conv2D(in_channels=384, out_channels=64, kernel_size=[1, 1])
        self.conv27 = paddle.nn.Conv2D(in_channels=64, out_channels=384, kernel_size=[1, 1])
        self.conv28 = paddle.nn.Conv2D(in_channels=384, out_channels=384, kernel_size=[3, 3], padding=1, groups=384)
        self.conv29 = paddle.nn.Conv2D(in_channels=384, out_channels=64, kernel_size=[1, 1])
        self.conv30 = paddle.nn.Conv2D(in_channels=64, out_channels=384, kernel_size=[1, 1])
        self.conv31 = paddle.nn.Conv2D(in_channels=384, out_channels=384, kernel_size=[3, 3], padding=1, groups=384)
        self.conv32 = paddle.nn.Conv2D(in_channels=384, out_channels=96, kernel_size=[1, 1])
        self.conv33 = paddle.nn.Conv2D(in_channels=96, out_channels=576, kernel_size=[1, 1])
        self.conv34 = paddle.nn.Conv2D(in_channels=576, out_channels=576, kernel_size=[3, 3], padding=1, groups=576)
        self.conv35 = paddle.nn.Conv2D(in_channels=576, out_channels=96, kernel_size=[1, 1])
        self.conv36 = paddle.nn.Conv2D(in_channels=96, out_channels=576, kernel_size=[1, 1])
        self.conv37 = paddle.nn.Conv2D(in_channels=576, out_channels=576, kernel_size=[3, 3], padding=1, groups=576)
        self.conv38 = paddle.nn.Conv2D(in_channels=576, out_channels=96, kernel_size=[1, 1])
        self.conv39 = paddle.nn.Conv2D(in_channels=96, out_channels=576, kernel_size=[1, 1])
        self.conv40 = paddle.nn.Conv2D(in_channels=576, out_channels=576, kernel_size=[3, 3], stride=2, padding=1, groups=576)
        self.conv41 = paddle.nn.Conv2D(in_channels=576, out_channels=160, kernel_size=[1, 1])
        self.conv42 = paddle.nn.Conv2D(in_channels=160, out_channels=960, kernel_size=[1, 1])
        self.conv43 = paddle.nn.Conv2D(in_channels=960, out_channels=960, kernel_size=[3, 3], padding=1, groups=960)
        self.conv44 = paddle.nn.Conv2D(in_channels=960, out_channels=160, kernel_size=[1, 1])
        self.conv45 = paddle.nn.Conv2D(in_channels=160, out_channels=960, kernel_size=[1, 1])
        self.conv46 = paddle.nn.Conv2D(in_channels=960, out_channels=960, kernel_size=[3, 3], padding=1, groups=960)
        self.conv47 = paddle.nn.Conv2D(in_channels=960, out_channels=160, kernel_size=[1, 1])
        self.conv48 = paddle.nn.Conv2D(in_channels=160, out_channels=960, kernel_size=[1, 1])
        self.conv49 = paddle.nn.Conv2D(in_channels=960, out_channels=960, kernel_size=[3, 3], padding=1, groups=960)
        self.conv50 = paddle.nn.Conv2D(in_channels=960, out_channels=320, kernel_size=[1, 1])
        self.conv51 = paddle.nn.Conv2D(in_channels=320, out_channels=1280, kernel_size=[1, 1])
        self.pool0 = paddle.nn.AdaptiveAvgPool2D(output_size=[1, 1])

    def forward(self, x2paddle_input_1):
        x2paddle_classifier_1_weight = self.x2paddle_classifier_1_weight
        x2paddle_classifier_1_bias = self.x2paddle_classifier_1_bias
        x2paddle__features_features_0_features_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_0_features_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_1_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_1_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_2_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_2_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_2_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_2_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_3_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_3_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_3_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_3_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_4_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_4_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_4_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_4_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_5_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_5_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_5_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_5_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_6_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_6_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_6_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_6_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_7_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_7_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_7_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_7_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_8_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_8_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_8_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_8_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_9_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_9_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_9_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_9_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_10_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_10_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_10_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_10_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_11_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_11_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_11_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_11_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_12_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_12_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_12_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_12_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_13_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_13_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_13_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_13_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_14_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_14_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_14_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_14_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_15_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_15_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_15_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_15_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_16_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_16_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_16_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_16_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_17_conv_conv_0_conv_0_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_17_conv_conv_0_conv_0_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_17_conv_conv_1_conv_1_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_17_conv_conv_1_conv_1_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_18_features_18_2_Constant_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=0.0)
        x2paddle__features_features_18_features_18_2_Constant_1_output_0 = paddle.full(dtype='float32', shape=[1], fill_value=6.0)
        x2paddle__features_features_0_features_0_0_Conv_output_0 = self.conv0(x2paddle_input_1)
        x2paddle__features_features_0_features_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_0_features_0_0_Conv_output_0, min=x2paddle__features_features_0_features_0_2_Constant_output_0, max=x2paddle__features_features_0_features_0_2_Constant_1_output_0)
        x2paddle__features_features_1_conv_conv_0_conv_0_0_Conv_output_0 = self.conv1(x2paddle__features_features_0_features_0_2_Clip_output_0)
        x2paddle__features_features_1_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_1_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_1_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_1_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_1_conv_conv_1_Conv_output_0 = self.conv2(x2paddle__features_features_1_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_2_conv_conv_0_conv_0_0_Conv_output_0 = self.conv3(x2paddle__features_features_1_conv_conv_1_Conv_output_0)
        x2paddle__features_features_2_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_2_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_2_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_2_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_2_conv_conv_1_conv_1_0_Conv_output_0 = self.conv4(x2paddle__features_features_2_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_2_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_2_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_2_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_2_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_2_conv_conv_2_Conv_output_0 = self.conv5(x2paddle__features_features_2_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_3_conv_conv_0_conv_0_0_Conv_output_0 = self.conv6(x2paddle__features_features_2_conv_conv_2_Conv_output_0)
        x2paddle__features_features_3_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_3_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_3_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_3_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_3_conv_conv_1_conv_1_0_Conv_output_0 = self.conv7(x2paddle__features_features_3_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_3_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_3_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_3_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_3_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_3_conv_conv_2_Conv_output_0 = self.conv8(x2paddle__features_features_3_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_3_Add_output_0 = paddle.add(x=x2paddle__features_features_2_conv_conv_2_Conv_output_0, y=x2paddle__features_features_3_conv_conv_2_Conv_output_0)
        x2paddle__features_features_4_conv_conv_0_conv_0_0_Conv_output_0 = self.conv9(x2paddle__features_features_3_Add_output_0)
        x2paddle__features_features_4_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_4_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_4_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_4_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_4_conv_conv_1_conv_1_0_Conv_output_0 = self.conv10(x2paddle__features_features_4_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_4_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_4_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_4_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_4_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_4_conv_conv_2_Conv_output_0 = self.conv11(x2paddle__features_features_4_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_5_conv_conv_0_conv_0_0_Conv_output_0 = self.conv12(x2paddle__features_features_4_conv_conv_2_Conv_output_0)
        x2paddle__features_features_5_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_5_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_5_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_5_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_5_conv_conv_1_conv_1_0_Conv_output_0 = self.conv13(x2paddle__features_features_5_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_5_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_5_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_5_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_5_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_5_conv_conv_2_Conv_output_0 = self.conv14(x2paddle__features_features_5_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_5_Add_output_0 = paddle.add(x=x2paddle__features_features_4_conv_conv_2_Conv_output_0, y=x2paddle__features_features_5_conv_conv_2_Conv_output_0)
        x2paddle__features_features_6_conv_conv_0_conv_0_0_Conv_output_0 = self.conv15(x2paddle__features_features_5_Add_output_0)
        x2paddle__features_features_6_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_6_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_6_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_6_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_6_conv_conv_1_conv_1_0_Conv_output_0 = self.conv16(x2paddle__features_features_6_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_6_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_6_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_6_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_6_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_6_conv_conv_2_Conv_output_0 = self.conv17(x2paddle__features_features_6_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_6_Add_output_0 = paddle.add(x=x2paddle__features_features_5_Add_output_0, y=x2paddle__features_features_6_conv_conv_2_Conv_output_0)
        x2paddle__features_features_7_conv_conv_0_conv_0_0_Conv_output_0 = self.conv18(x2paddle__features_features_6_Add_output_0)
        x2paddle__features_features_7_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_7_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_7_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_7_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_7_conv_conv_1_conv_1_0_Conv_output_0 = self.conv19(x2paddle__features_features_7_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_7_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_7_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_7_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_7_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_7_conv_conv_2_Conv_output_0 = self.conv20(x2paddle__features_features_7_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_8_conv_conv_0_conv_0_0_Conv_output_0 = self.conv21(x2paddle__features_features_7_conv_conv_2_Conv_output_0)
        x2paddle__features_features_8_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_8_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_8_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_8_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_8_conv_conv_1_conv_1_0_Conv_output_0 = self.conv22(x2paddle__features_features_8_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_8_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_8_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_8_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_8_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_8_conv_conv_2_Conv_output_0 = self.conv23(x2paddle__features_features_8_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_8_Add_output_0 = paddle.add(x=x2paddle__features_features_7_conv_conv_2_Conv_output_0, y=x2paddle__features_features_8_conv_conv_2_Conv_output_0)
        x2paddle__features_features_9_conv_conv_0_conv_0_0_Conv_output_0 = self.conv24(x2paddle__features_features_8_Add_output_0)
        x2paddle__features_features_9_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_9_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_9_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_9_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_9_conv_conv_1_conv_1_0_Conv_output_0 = self.conv25(x2paddle__features_features_9_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_9_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_9_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_9_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_9_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_9_conv_conv_2_Conv_output_0 = self.conv26(x2paddle__features_features_9_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_9_Add_output_0 = paddle.add(x=x2paddle__features_features_8_Add_output_0, y=x2paddle__features_features_9_conv_conv_2_Conv_output_0)
        x2paddle__features_features_10_conv_conv_0_conv_0_0_Conv_output_0 = self.conv27(x2paddle__features_features_9_Add_output_0)
        x2paddle__features_features_10_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_10_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_10_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_10_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_10_conv_conv_1_conv_1_0_Conv_output_0 = self.conv28(x2paddle__features_features_10_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_10_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_10_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_10_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_10_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_10_conv_conv_2_Conv_output_0 = self.conv29(x2paddle__features_features_10_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_10_Add_output_0 = paddle.add(x=x2paddle__features_features_9_Add_output_0, y=x2paddle__features_features_10_conv_conv_2_Conv_output_0)
        x2paddle__features_features_11_conv_conv_0_conv_0_0_Conv_output_0 = self.conv30(x2paddle__features_features_10_Add_output_0)
        x2paddle__features_features_11_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_11_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_11_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_11_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_11_conv_conv_1_conv_1_0_Conv_output_0 = self.conv31(x2paddle__features_features_11_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_11_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_11_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_11_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_11_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_11_conv_conv_2_Conv_output_0 = self.conv32(x2paddle__features_features_11_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_12_conv_conv_0_conv_0_0_Conv_output_0 = self.conv33(x2paddle__features_features_11_conv_conv_2_Conv_output_0)
        x2paddle__features_features_12_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_12_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_12_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_12_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_12_conv_conv_1_conv_1_0_Conv_output_0 = self.conv34(x2paddle__features_features_12_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_12_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_12_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_12_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_12_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_12_conv_conv_2_Conv_output_0 = self.conv35(x2paddle__features_features_12_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_12_Add_output_0 = paddle.add(x=x2paddle__features_features_11_conv_conv_2_Conv_output_0, y=x2paddle__features_features_12_conv_conv_2_Conv_output_0)
        x2paddle__features_features_13_conv_conv_0_conv_0_0_Conv_output_0 = self.conv36(x2paddle__features_features_12_Add_output_0)
        x2paddle__features_features_13_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_13_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_13_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_13_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_13_conv_conv_1_conv_1_0_Conv_output_0 = self.conv37(x2paddle__features_features_13_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_13_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_13_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_13_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_13_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_13_conv_conv_2_Conv_output_0 = self.conv38(x2paddle__features_features_13_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_13_Add_output_0 = paddle.add(x=x2paddle__features_features_12_Add_output_0, y=x2paddle__features_features_13_conv_conv_2_Conv_output_0)
        x2paddle__features_features_14_conv_conv_0_conv_0_0_Conv_output_0 = self.conv39(x2paddle__features_features_13_Add_output_0)
        x2paddle__features_features_14_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_14_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_14_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_14_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_14_conv_conv_1_conv_1_0_Conv_output_0 = self.conv40(x2paddle__features_features_14_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_14_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_14_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_14_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_14_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_14_conv_conv_2_Conv_output_0 = self.conv41(x2paddle__features_features_14_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_15_conv_conv_0_conv_0_0_Conv_output_0 = self.conv42(x2paddle__features_features_14_conv_conv_2_Conv_output_0)
        x2paddle__features_features_15_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_15_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_15_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_15_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_15_conv_conv_1_conv_1_0_Conv_output_0 = self.conv43(x2paddle__features_features_15_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_15_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_15_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_15_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_15_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_15_conv_conv_2_Conv_output_0 = self.conv44(x2paddle__features_features_15_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_15_Add_output_0 = paddle.add(x=x2paddle__features_features_14_conv_conv_2_Conv_output_0, y=x2paddle__features_features_15_conv_conv_2_Conv_output_0)
        x2paddle__features_features_16_conv_conv_0_conv_0_0_Conv_output_0 = self.conv45(x2paddle__features_features_15_Add_output_0)
        x2paddle__features_features_16_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_16_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_16_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_16_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_16_conv_conv_1_conv_1_0_Conv_output_0 = self.conv46(x2paddle__features_features_16_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_16_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_16_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_16_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_16_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_16_conv_conv_2_Conv_output_0 = self.conv47(x2paddle__features_features_16_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_16_Add_output_0 = paddle.add(x=x2paddle__features_features_15_Add_output_0, y=x2paddle__features_features_16_conv_conv_2_Conv_output_0)
        x2paddle__features_features_17_conv_conv_0_conv_0_0_Conv_output_0 = self.conv48(x2paddle__features_features_16_Add_output_0)
        x2paddle__features_features_17_conv_conv_0_conv_0_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_17_conv_conv_0_conv_0_0_Conv_output_0, min=x2paddle__features_features_17_conv_conv_0_conv_0_2_Constant_output_0, max=x2paddle__features_features_17_conv_conv_0_conv_0_2_Constant_1_output_0)
        x2paddle__features_features_17_conv_conv_1_conv_1_0_Conv_output_0 = self.conv49(x2paddle__features_features_17_conv_conv_0_conv_0_2_Clip_output_0)
        x2paddle__features_features_17_conv_conv_1_conv_1_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_17_conv_conv_1_conv_1_0_Conv_output_0, min=x2paddle__features_features_17_conv_conv_1_conv_1_2_Constant_output_0, max=x2paddle__features_features_17_conv_conv_1_conv_1_2_Constant_1_output_0)
        x2paddle__features_features_17_conv_conv_2_Conv_output_0 = self.conv50(x2paddle__features_features_17_conv_conv_1_conv_1_2_Clip_output_0)
        x2paddle__features_features_18_features_18_0_Conv_output_0 = self.conv51(x2paddle__features_features_17_conv_conv_2_Conv_output_0)
        x2paddle__features_features_18_features_18_2_Clip_output_0 = paddle.clip(x=x2paddle__features_features_18_features_18_0_Conv_output_0, min=x2paddle__features_features_18_features_18_2_Constant_output_0, max=x2paddle__features_features_18_features_18_2_Constant_1_output_0)
        x2paddle__GlobalAveragePool_output_0 = self.pool0(x2paddle__features_features_18_features_18_2_Clip_output_0)
        x2paddle__Flatten_output_0 = paddle.reshape(x=x2paddle__GlobalAveragePool_output_0, shape=[1, 1280])
        x2paddle_536_mm = paddle.matmul(x=x2paddle__Flatten_output_0, y=x2paddle_classifier_1_weight, transpose_y=True)
        x2paddle_536 = paddle.add(x=x2paddle_536_mm, y=x2paddle_classifier_1_bias)
        return x2paddle_536

def main(x2paddle_input_1):
    # There are 1 inputs.
    # x2paddle_input_1: shape-[1, 3, 224, 224], type-float32.
    paddle.disable_static()
    params = paddle.load(r'D:\Project\classify-chat-history\pd_model\model.pdparams')
    model = ONNXModel()
    model.set_dict(params, use_structured_name=True)
    model.eval()
    out = model(x2paddle_input_1)
    return out
